//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Engine.cpp
//  @ Date : 05.06.2016
//  @ Author : 
//
//


#include "Engine.h"
#include "ISystem.h"

void Engine::Update(float time)
{
	for (auto system : _systems)
	{
		system->Update(time);
	}
}

void Engine::AddSystem(ISystem* system) 
{
	if (system != nullptr)
	{
		_systems.push_back(system);
		system->Start();
	}
}

void Engine::RemoveSystem(ISystem* system) 
{
	if (system != nullptr)
	{
		system->Finish();
		_systems.remove(system);
	}
}

void Engine::AddEntity(IEntity* entity) 
{
	if (entity != nullptr)
	{
		_entities.push_back(entity);

		for (auto system : _systems)
		{
			system->AddComponentFromEntity(entity);
		}
	}
}

void Engine::RemoveEntity(IEntity* entity) 
{
	if (entity != nullptr)
	{
		_entities.remove(entity);

		for (auto system : _systems)
		{
			system->RemoveComponentFromEntity(entity);
		}
	}
}