//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ISystem.h
//  @ Date : 05.06.2016
//  @ Author : 
//
//


#if !defined(_ISYSTEM_H)
#define _ISYSTEM_H

#include "IEntity.h"

class ISystem 
{
public:
	virtual void Start() = 0;
	virtual void Finish() = 0;
	virtual void Update(float time) = 0;

	virtual bool AddComponentFromEntity(IEntity* entity) = 0;
	virtual bool RemoveComponentFromEntity(IEntity* entity) = 0;
};


#endif  //_ISYSTEM_H

