//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MoveSystem.h
//  @ Date : 05.06.2016
//  @ Author : 
//
//


#if !defined(_MOVESYSTEM_H)
#define _MOVESYSTEM_H

#include "ISystem.h"
#include "VelocityComponent.h"
#include <list>

class MoveSystem : public ISystem
{
private:
	std::list <VelocityComponent*> _velocityComponents;

public:
	virtual void Start() override;
	virtual void Finish() override;

	virtual void Update(float time) override;

	virtual bool AddComponentFromEntity(IEntity* entity) override;
	virtual bool RemoveComponentFromEntity(IEntity* entity) override;

	virtual void AddComponent(VelocityComponent* component);
	virtual void RemoveComponent(VelocityComponent* component);
};

#endif  //_MOVESYSTEM_H
