//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : RenderNode.h
//  @ Date : 05.06.2016
//  @ Author : 
//
//


#if !defined(_RENDERNODE_H)
#define _RENDERNODE_H

#include "TransformComponent.h"
#include "DisplayComponent.h"
#include "IEntity.h"

struct RenderNode 
{
	TransformComponent* Transform;
	DisplayComponent*	Display;

	RenderNode() :
		Transform(nullptr),
		Display(nullptr)
	{
	}

	bool InitByEntity(IEntity* entity)
	{
		Transform = entity->GetComponent<TransformComponent>();
		Display = entity->GetComponent<DisplayComponent>();

		if (Display != nullptr && Transform != nullptr)
			return true;

		return false;
	}
};

#endif  //_RENDERNODE_H
